name: Car Parking System (Composite CI)

on:
  pull_request:
    branches: ["main", "develop"]
  # push:
  #   branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  car-parking-system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run composite CI action
        uses: .github/actions/ci
        with:
          go-version: "1.25"
          working-directory: "."
          golangci-lint-version: "v2.11"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v6
        with:
          name: car-parking-system-coverage
          path: ./coverage.out
          if-no-files-found: error